// Generated by https://quicktype.io

export interface PlacesResponse {
  type:        string;
  query:       string[];
  features:    Feature[];
  attribution: string;
}

export interface Feature {
  id:            string;
  type:          string;
  place_type:    string[];
  relevance:     number;
  properties:    Properties;
  text_es:       string;
  language_es?:  Language;
  place_name_es: string;
  text:          string;
  language?:     Language;
  place_name:    string;
  bbox?:         number[];
  center:        number[];
  geometry:      Geometry;
  context:       Context[];
}

export interface Context {
  id:           string;
  mapbox_id:    string;
  text_es:      string;
  text:         string;
  language_es?: Language;
  language?:    Language;
  wikidata?:    string;
  short_code?:  Language;
}

export enum Language {
  Es = "es",
  EsM = "ES-M",
}

export interface Geometry {
  type:        string;
  coordinates: number[];
}

export interface Properties {
  wikidata?:   string;
  mapbox_id?:  string;
  foursquare?: string;
  landmark?:   boolean;
  address?:    string;
  category?:   string;
}
